{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.my.user.themes;
in
{
  options.my.user.themes = {
    enable = lib.mkEnableOption "Custom Themes";
  };

  config = lib.mkIf cfg.enable {

    # 1. Konfigurasi Kursor Vimix White
    home.pointerCursor = {
      name = "Vimix-white-cursors";
      package = pkgs.vimix-cursors;
      size = 24; # Adjust size as needed
      gtk.enable = true;
      x11.enable = true; # Ensures consistent cursor over XWayland apps
    };

    # 2. Konfigurasi GTK (Brave, aplikasi GNOME, dll)
    gtk = {
      enable = true;
      gtk4.theme = config.gtk.theme;
      theme = {
        # Theme folder name generated by Nix
        name = "Colloid-Dark";
        # Using Nix override to inject customization
        package = pkgs.colloid-gtk-theme.override {
          colorVariants = [ "dark" ];
          tweaks = [ "normal" ];
        };
      };

      iconTheme = {
        name = "Tela-circle-dark";
        package = pkgs.tela-circle-icon-theme;
      };

      font = {
        name = "Adwaita Mono";
        size = 10;
      };
    };

    xdg.mimeApps = {
      enable = true;
      defaultApplications = {
        # Browser Default
        "text/html" = "firefox.desktop";
        "x-scheme-handler/http" = "firefox.desktop";
        "x-scheme-handler/https" = "firefox.desktop";
        "x-scheme-handler/about" = "firefox.desktop";
        "x-scheme-handler/unknown" = "firefox.desktop";

        # PDF Viewer
        "application/pdf" = "org.pwmt.zathura.desktop";
        # "application/pdf" = "org.pwmt.zathura-pdf-mupdf.desktop";

        # Text & Code
        "text/plain" = "dev.zed.Zed.desktop";
        "application/javascript" = "dev.zed.Zed.desktop";
        "application/json" = "dev.zed.Zed.desktop";
        "text/x-script.python" = "dev.zed.Zed.desktop";

        "text/x-markdown" = "dev.zed.Zed.desktop";
        "text/x-csrc" = "dev.zed.Zed.desktop";
        "text/x-chdr" = "dev.zed.Zed.desktop";
        "text/x-shellscript" = "dev.zed.Zed.desktop";

        # Image & Video
        "image/png" = "org.kde.gwenview.desktop";
        "image/jpeg" = "org.kde.gwenview.desktop";
        "video/mp4" = "mpv.desktop";
      };
    };

    home.sessionVariables = {
      EDITOR = "zeditor -w";
      BROWSER = "firefox";

      # Force Qt apps to run natively on Wayland
      QT_QPA_PLATFORM = "wayland;xcb";

      # Disable Qt window decorations under Wayland
      QT_WAYLAND_DISABLE_WINDOWDECORATION = "1";

    };
  };
}
