image: nixos/nix:latest

variables:
  NIX_CONFIG: "experimental-features = nix-command flakes"

before_script:
  - nix-env -iA nixpkgs.cachix
  - cachix use cachixix

flake_check:
  script:
    - nix flake check -L

build_packages:
  script:
    - cachix watch-exec cachixix -- nix build \
      ".#caelestia" \
      ".#llama" \
      -L
