# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

let
  mainDevice = "/dev/disk/by-uuid/f888825f-bdb2-4dca-9c58-b5dd4f6a39d8";
  commonBtrfsOpts = [
    "compress=zstd:3"
    "noatime"
    "discard=async"
    "space_cache=v2"
    "commit=120"
    "ssd"
  ];
  mkBtrfsSubvol = subvol: [ "subvol=${subvol}" ] ++ commonBtrfsOpts;
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "ehci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ];
    };
    binfmt.emulatedSystems = [ "aarch64-linux" ];
    kernelModules = [ ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = mainDevice;
      fsType = "btrfs";
      options = mkBtrfsSubvol "@nixos-root";
    };

    "/nix" = {
      device = mainDevice;
      fsType = "btrfs";
      options = mkBtrfsSubvol "@nixos-nix";
    };

    "/home" = {
      device = mainDevice;
      fsType = "btrfs";
      options = mkBtrfsSubvol "@nixos-home";
      neededForBoot = true;
    };

    "/persist" = {
      device = mainDevice;
      fsType = "btrfs";
      options = mkBtrfsSubvol "@nixos-persist";
      neededForBoot = true;
    };

    "/var/log" = {
      device = mainDevice;
      fsType = "btrfs";
      options = mkBtrfsSubvol "@nixos-log";
      neededForBoot = true;
    };

    "/boot" = {
      device = mainDevice;
      fsType = "btrfs";
      options = mkBtrfsSubvol "@nixos-boot";
    };

    "/boot/efi" = {
      device = "/dev/disk/by-uuid/CF4A-0A6F";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;
}
