# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ehci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9617790f-27d0-460e-8f00-fa94f1d0e68d";
    fsType = "btrfs";
    options = [
      "subvol=@nixos-root"
      "compress=zstd:3"
      "noatime"
      "discard=async"
      "space_cache=v2"
      "commit=120"
      "ssd" # Memaksa optimasi Solid State Drive
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/9617790f-27d0-460e-8f00-fa94f1d0e68d";
    fsType = "btrfs";
    options = [
      "subvol=@nixos-nix"
      "compress=zstd:6"
      "noatime"
      "discard=async"
      "space_cache=v2"
      "commit=120"
      "ssd" # Memaksa optimasi Solid State Drive
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/9617790f-27d0-460e-8f00-fa94f1d0e68d";
    fsType = "btrfs";
    options = [
      "subvol=@nixos-home"
      "compress=zstd:3"
      "noatime"
      "discard=async"
      "space_cache=v2"
      "ssd" # Memaksa optimasi Solid State Drive
    ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/9617790f-27d0-460e-8f00-fa94f1d0e68d";
    fsType = "btrfs";
    options = [
      "subvol=@nixos-persist"
      "compress=zstd:3"
      "noatime" # Mencegah OS menulis log setiap kali file HANYA dibaca
      "discard=async" # Mengatur TRIM agar berjalan di latar belakang
      "space_cache=v2" # Mempercepat mounting dan pencarian ruang kosong di BTRFS
      "commit=120" # Menahan write ke disk selama 2 menit
      "ssd" # Memaksa optimasi Solid State Drive
    ];
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/9617790f-27d0-460e-8f00-fa94f1d0e68d";
    fsType = "btrfs";
    options = [
      "subvol=@nixos-log"
      "compress=zstd:3"
      "noatime"
      "discard=async"
      "space_cache=v2"
      "commit=120"
      "ssd" # Memaksa optimasi Solid State Drive
    ];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9617790f-27d0-460e-8f00-fa94f1d0e68d";
    fsType = "btrfs";
    options = [
      "subvol=@nixos-boot"
      "compress=zstd:3"
      "noatime"
      "discard=async"
      "space_cache=v2"
      "commit=120"
      "ssd" # Memaksa optimasi Solid State Drive
    ];
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/5ABE-6680";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;
  hardware.steam-hardware.enable = true;
}
