Host openwrt-old
    Hostname 192.168.5.1
    User root
    Port 22
    HostKeyAlgorithms +ssh-rsa
    PubkeyAcceptedKeyTypes +ssh-rsa
    IdentityFile ~/.ssh/id_rsa_compat

Host mido
    Hostname 192.168.5.224
    User klein
    Port 22

Host nikel-termux
    Hostname 192.168.5.187
    User u0_a90
    Port 8022

Host rolex-termux
    Hostname 192.168.5.198
    User u0_a225
    Port 8022
    IdentityFile ~/.ssh/id_rsa_compat
Host rolex-userland
    Hostname 192.168.5.198
    User sshuser
    Port 2022
    IdentityFile ~/.ssh/id_rsa_compat

Host sumnag-termux
    Hostname 192.168.5.241
    User u0_a185
    Port 8022
    IdentityFile ~/.ssh/id_rsa_compat

Host nikel-linux
    Hostname 192.168.5.120
    User klein
    Port 2222
    IdentityFile ~/.ssh/id_rsa_compat

Host stb
    HostName 192.168.5.207
    User klein
    IdentityFile ~/.ssh/id_rsa_compat
