[Audio]
PreferredLanguage=eng, id
PreferredTrack=5
Volume=100

[General]
ColorScheme=ColloidNordDark
LastPlayedFile=file:///mnt/data/record/2026-03-18 21-59-58.mkv
RememberWindowGeometry=true

[Playback]
HWDecoding=auto-safe
MinDurationToSavePosition=0
PauseWhileMinimized=true
RestoreFilePosition=true
SavePositionInterval=5
YtdlFormat=bestvideo[height<=1080][vcodec^=avc]+bestaudio[language^=id]/bestvideo[height<=1080][vcodec^=avc]+bestaudio/bestvideo[height<=720][vcodec^=avc]+bestaudio
