name: "Build and Cache Nix Packages"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        install_url: https://nixos.org/nix/install

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v14
      with:
        name: cachixix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build Caelestia Shell
      run: nix build ".#homeConfigurations.\"klein-moretti@KleinMoretti\".config.programs.caelestia.package" --print-build-logs

    - name: Build Dank Material Shell
      run: nix build ".#homeConfigurations.\"klein-moretti@KleinMoretti\".config.programs.dank-material-shell.package" --print-build-logs
